#!/usr/bin/env python

# This isn't really a script, it's a utility.
##
# This is a utility that you can use to put any file
# under a central repository. It is meant to be used
# for config files that could be all over the system.
##
# The utility will:
## 1. make a copy of the added file
## 2. copy the file to the central repo
## 3. replace the original file with a symlink
##
# author: @mehulkar

import sys, os, shutil

# TODO only print usage statement on incorrect usage
print("Usage: confcontrol add <file>")

# Get the file arg
file = sys.argv[2]

# directory where we'll host all the files
# TODO Maybe this shouldn't be hardcoded?
confcontrol_dir = os.path.expanduser("~") + "/etc/confcontrol"

# Let's create it, if it doesn't exist already
if not os.path.exists(confcontrol_dir):
    print("Making " + confcontrol_dir)
    os.makedirs(confcontrol_dir)

# Copy $file to the $confcontrol_dir
shutil.copyfile(file, confcontrol_dir + "/" + file)

# Make a backup of file where it is
os.rename(file, file + ".confcontrol.bak")

# Make a symlink to the copied file from $confcontrol_dir in the place it should be
os.symlink(confcontrol_dir + "/" + file, file)
