#!/usr/bin/env python

# I only did this with python because I
# didn't want to look up how to do bash arguments again
# And because I never use python, so I thought it would be cool.
# Author: mehulkar

import sys
import os
import shutil

# Usage
# TODO only print this if it was used incorrectly
print("Usage: confcontrol add <file>")

# Get the file arg
file = sys.argv[2]

# directory where we'll host all the files
confcontrol_dir = os.path.expanduser("~") + "/etc/confcontrol"

# Let's create it, if it doesn't exist already
if not os.path.exists(confcontrol_dir):
    print("Making " + confcontrol_dir)
    os.makedirs(confcontrol_dir)

# Copy $file to the $confcontrol_dir
shutil.copyfile(file, confcontrol_dir + "/" + file)

# Make a backup of file where it is
os.rename(file, file + ".confcontrol.bak")

# Make a symlink to the copied file from $confcontrol_dir in the place it should be
os.symlink(confcontrol_dir + "/" + file, file)

# TODO
# 1. Check if the file you care about exists
# 2. Fail if first argument isn't add
# 3. Add a rm commmand also
# 4. Don't hard code the $confcontrol_dir
# 5. git init in $confcontrol_dir on first create
# 6. git add after new cp into $confcontrol_dir
